_format_version: "2.1"
_transform: true

services:
  - name: auth-v1
    url: http://auth:9999
    routes:
      - name: auth-v1-all
        strip_path: true
        paths:
          - /auth/v1
    plugins:
      - name: cors
      - name: request-transformer
        config:
          add:
            headers:
              - "X-Client-Info: supabase-js/1.0.0"
  - name: rest-v1
    url: http://rest:3000
    routes:
      - name: rest-v1-all
        strip_path: true
        paths:
          - /rest/v1
    plugins:
      - name: cors
      - name: request-transformer
        config:
          add:
            headers:
              - "X-Client-Info: supabase-js/1.0.0"
  - name: realtime-v1
    url: http://realtime:4000
    routes:
      - name: realtime-v1-all
        strip_path: true
        paths:
          - /realtime/v1
    plugins:
      - name: cors
      - name: request-transformer
        config:
          add:
            headers:
              - "X-Client-Info: supabase-js/1.0.0"
  - name: storage-v1
    url: http://storage:5000
    routes:
      - name: storage-v1-all
        strip_path: true
        paths:
          - /storage/v1
    plugins:
      - name: cors
      - name: request-transformer
        config:
          add:
            headers:
              - "X-Client-Info: supabase-js/1.0.0"
  - name: meta
    url: http://meta:8080
    routes:
      - name: meta-all
        strip_path: true
        paths:
          - /pg
    plugins:
      - name: cors
      - name: request-transformer
        config:
          add:
            headers:
              - "X-Client-Info: supabase-js/1.0.0" 