version: '3.9'
services:
  evolution-api:
    container_name: evolution_api
    image: atendai/evolution-api:latest
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - evolution_instances:/evolution/instances
      - evolution_store:/evolution/store
      - postgres_data:/var/lib/postgresql/data

 